config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /fr|en/ do
    get 'contacteznous', to: 'pages#contacteznous', as: :contacteznous
    get 'mentionslegales', to: 'pages#mentionslegales', as: :mentionslegales
    get 'lesgites', to: 'pages#lesgites', as: :lesgites
    get 'grenierdesanges', to: 'pages#grenierdesanges', as: :grenierdesanges
    get 'gitedelavigne', to: 'pages#gitedelavigne', as: :gitedelavigne
    get 'evenements', to: 'pages#evenements', as: :evenements
    get 'region', to: 'pages#region', as: :region
    get 'commentvenir', to: 'pages#commentvenir', as: :commentvenir
    get 'reserver', to: 'pages#reserver', as: :reserver
    get 'admin', to: 'pages#admin', as: :admin
    get 'resas/new'
    get 'resas/create'
    get 'resas/edit'
    get 'resas/update'
    get 'resas/destroy'
    devise_for :users
    root to: 'pages#home'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gite.rb
class Gite < ApplicationRecord
  has_many :resas, dependent: :destroy
end

app/models/resa.rb
class Resa < ApplicationRecord
  belongs_to :gite
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
    { locale: I18n.locale }
  end

  # Make sure your production HOST variable is set with your domain name. If you deploy your code with Heroku for instance, just type in your terminal heroku config:set HOST=www.my_product.com
    private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:admin]

  def home

  end

  def commentvenir

  end

  def evenements

  end

  def lesgites

  end

  def grenierdesanges

  end

  def gitedelavigne

  end

  def region

  end

  def reserver

  end

  def mentionslegales

  end

  def admin


  end

  def contacteznous

  end

end

app/controllers/resas_controller.rb
class ResasController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
   <link href="https://fonts.googleapis.com/css?family=Cormorant+Unicase:400,700|Just+Another+Hand" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/admin.html.erb
admin.html.erb

app/views/pages/commentvenir.html.erb
<div class="barimage2"></div>
<div class="container" style="text-align:center;">
  <h1 >COMMENT VOUS RENDRE AU MAS DES ANGES - MENERBES</h1>
  <br>
  <%= simple_format(t(:CV1)) %>
  <br>
  &nbsp;<h1 class="adresse"><i class="fas fa-map-marker-alt"></i> 1045 route de Cavaillon - Lieu-dit Le Camp - CD n° 3 <br> 84560 MENERBES</h1> &nbsp;
  <div id="map" class="leafletmap"></div>
</div>

 <script src="https://unpkg.com/leaflet@1.5.0/dist/leaflet.js"
   integrity="sha512-3Wcxp7F9bV2pl+MBgrL6Pz7AJASLpemmQPIiPA0lDs3ImF0z4JuuMIBPeirLbgIuhfH2gJyGWZjvm6M+Zr7L6Q=="
   crossorigin=""></script>

app/views/pages/contacteznous.html.erb
contacteznous.html.erb

app/views/pages/evenements.html.erb
evenements.html.erb

app/views/pages/gitedelavigne.html.erb
gitedelavigne.html.erb

app/views/pages/grenierdesanges.html.erb
grenierdesanges.html.erb

app/views/pages/home.html.erb
<div
  class="test banner"
  data-slides='[
    "assets/OLIVIER_ET_LAVANDE_AU_BORD_DE_LA_PISCINE.JPG",
    "assets/ENTREE.JPG",
    "assets/IRIS3.JPG",
    "assets/LE_MAS_DES_ANGES_LENTREE.JPG",
    "assets/QUELLE_TRANQUILITE.JPG",
    "assets/SENTEURS_DE_PROVENCE_AU_BORD_DE_LEAU.JPG",
    "assets/TOUTE_LA_PROVENCE.JPG",
    "assets/UNE_PARTIE_DE_PETANQUE.JPG",
    "assets/UN_COIN_DE_REPOS.JPG"
  ]'
>
  <div class="banner-content">
    <h1 class="lemas">le mas </h1>
    <h1 class="desanges">DES ANGES</h1>
    <%= link_to "Réservez Ici", reserver_path, class:"btn btn-lg bouton" %>
    <%= link_to evenements_path, class:"evelink" do %>
    <div class="evenement-infos">
      <h3>Cet été dans le Lubéron</h3>
      <ul>
        <li>Festival du Lubéron à Lacoste et Ménerbes (musique classique)</li>
        <li>Festival d'Avignon (théâtre)</li>
        <li>Festival International de la Roque d'Anthéron (piano)</li>
      </ul>
    </div>
    <% end %>
  </div>
</div> <!-- /.primary -->

app/views/pages/lesgites.html.erb
<div class="barimage"></div>
<div class="container">
  <div class="masdesanges">
    <h1>LE MAS DES ANGES & MENERBES</h1>
    <%= simple_format(t(:MA1)) %>
    <div class="imgtext">
      <div class="textcarre">
        <%= simple_format(t(:MA2a)) %>
        <br>
        <%= simple_format(t(:MA2b)) %>
        <br>
        <%= simple_format(t(:MA2c)) %>
      </div>
      <%= image_tag "region/GORDES.JPG", class:"imgcarred" %>
    </div>
    <div class="imgtext">
      <%= image_tag "region/RUSTREL.JPG", class:"imgcarreg" %>
      <div class="textcarre">
        <%= simple_format(t(:MA3a)) %>
      </div>
    </div>
    <%= simple_format(t(:MA3b)) %>
    <h1>Le Grenier des Anges & Le Gite de la Vigne</h1>
    <%= simple_format(t(:MA4)) %>
    <div class="imgtext">
      <%= image_tag "grenierdesanges/grenierdesanges1.JPG", class:"imgcarreg" %>
      <div class="textcarre">
        <%= simple_format(t(:GA1)) %>
        <%= link_to "Le Grenier Des Anges", grenierdesanges_path, class:"btn btn-lg bouton" %>
      </div>
    </div>
    <div class="imgtext">
      <%= image_tag "gitedelavigne/Gitedelavigne1.JPG", class:"imgcarreg" %>
      <div class="textcarre">
        <%= simple_format(t(:GV1)) %>
        <%= link_to "Le Gite De la Vigne", gitedelavigne_path, class:"btn btn-lg bouton" %>
      </div>
    </div>
    <%= simple_format(t(:MA5)) %> <br>
  </div>
</div>

app/views/pages/mentionslegales.html.erb
mentionslegales.html.erb

app/views/pages/region.html.erb
region.html.erb

app/views/pages/reserver.html.erb
reserver.html.erb

app/views/resas/create.html.erb
<h1>Resas#create</h1>
<p>Find me in app/views/resas/create.html.erb</p>

app/views/resas/destroy.html.erb
<h1>Resas#destroy</h1>
<p>Find me in app/views/resas/destroy.html.erb</p>

app/views/resas/edit.html.erb
<h1>Resas#edit</h1>
<p>Find me in app/views/resas/edit.html.erb</p>

app/views/resas/new.html.erb
<h1>Resas#new</h1>
<p>Find me in app/views/resas/new.html.erb</p>

app/views/resas/update.html.erb
<h1>Resas#update</h1>
<p>Find me in app/views/resas/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <%= t(:pied) %>
    <%= link_to t(:mentionslegales_link), mentionslegales_path, class:"mentions_link" %>
      -
    <%= link_to t(:contacteznous), contacteznous_path, class:"mentions_link" %>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
<!--   <a href="/" class="navbar-wagon-brand">
  </a> -->
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to t(:accueil), root_path, class:"navbar-wagon-item navbar-wagon-link" %>

    <div class="dropdown">
      <div class="dropbtn"><%= link_to t(:lemasdesanges), lesgites_path, class:"navbar-wagon-item navbar-wagon-link" %></div>
      <div class="dropdown-content">
        <%= link_to t(:grenier), grenierdesanges_path %>
        <%= link_to t(:gite), gitedelavigne_path %>
      </div>
    </div>
    <%= link_to t(:evenements), evenements_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(:region), region_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(:commentvenir), commentvenir_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(:reserver), reserver_path, class:"navbar-wagon-item navbar-wagon-link" %>
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to (image_tag "GB.png"), { :locale=>'en' } %>

    <% else %>
      <%= link_to (image_tag "FR.png"), { :locale=>'fr' } %>

    <%end%>
  </div>

    <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(:accueil), root_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(:lemasdesanges), lesgites_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(:evenements), evenements_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(:region), region_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(:commentvenir), commentvenir_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(:reserver), reserver_path, class:"navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to (image_tag "GB.png"), { :locale=>'en' } %>

      <% else %>
      <%= link_to (image_tag "FR.png"), { :locale=>'fr' } %>

    <%end%>
  </div>
</div>